# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.3.3+26.1.2
maven_group=io.github.foundationgames
archives_base_name=splinecart

# Dependencies
fabric_api_version=0.151.0+26.1.2
